// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpLY0z6fhSpJMS4Un1ynBy2CG45r9I8Zo',
    appId: '1:93418366351:web:41113d683534a5581497fa',
    messagingSenderId: '93418366351',
    projectId: 'fluttercomputacionmovil3',
    authDomain: 'fluttercomputacionmovil3.firebaseapp.com',
    storageBucket: 'fluttercomputacionmovil3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvoVqHxlUM2lQQ4SmMNpwdIgLuv2Xli08',
    appId: '1:93418366351:android:c5d9ffcefad12b011497fa',
    messagingSenderId: '93418366351',
    projectId: 'fluttercomputacionmovil3',
    storageBucket: 'fluttercomputacionmovil3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDFl_5HncGF2hXQ0Bzf7FcGH4ojaKsVu4',
    appId: '1:93418366351:ios:1f5ff12356f96c731497fa',
    messagingSenderId: '93418366351',
    projectId: 'fluttercomputacionmovil3',
    storageBucket: 'fluttercomputacionmovil3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDFl_5HncGF2hXQ0Bzf7FcGH4ojaKsVu4',
    appId: '1:93418366351:ios:1f5ff12356f96c731497fa',
    messagingSenderId: '93418366351',
    projectId: 'fluttercomputacionmovil3',
    storageBucket: 'fluttercomputacionmovil3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpLY0z6fhSpJMS4Un1ynBy2CG45r9I8Zo',
    appId: '1:93418366351:web:cb5ebbadee5d2c7b1497fa',
    messagingSenderId: '93418366351',
    projectId: 'fluttercomputacionmovil3',
    authDomain: 'fluttercomputacionmovil3.firebaseapp.com',
    storageBucket: 'fluttercomputacionmovil3.appspot.com',
  );
}
